export type GalleryCategory = "all" | "carpet" | "sofa" | "rug" | "stain";

export interface GalleryItem {
  id: string;
  type: "image" | "video";
  src: string;
  poster?: string;
  alt: string;
  title: string;
  category: GalleryCategory;
  aspect: "landscape" | "portrait" | "square";
}

export const GALLERY_CATEGORIES: { key: GalleryCategory; label: string }[] = [
  { key: "all", label: "All Work" },
  { key: "carpet", label: "Carpet Cleaning" },
  { key: "sofa", label: "Sofa & Upholstery" },
  { key: "rug", label: "Rug Care" },
  { key: "stain", label: "Stain Removal" },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  // --- VIDEOS ---
  {
    id: "v1",
    type: "video",
    src: "/videos/gallery/carpet-deep-cleaning-result-dubai.mp4",
    poster: "/videos/gallery/carpet-deep-cleaning-result-dubai-poster.jpg",
    alt: "Carpet deep cleaning result showing professional extraction process in Dubai",
    title: "Carpet Deep Cleaning Result",
    category: "carpet",
    aspect: "portrait",
  },
  {
    id: "v2",
    type: "video",
    src: "/videos/gallery/carpet-steam-cleaning-dubai.mp4",
    poster: "/videos/gallery/carpet-steam-cleaning-dubai-poster.jpg",
    alt: "Professional carpet steam cleaning process using hot water extraction in Dubai",
    title: "Carpet Steam Cleaning",
    category: "carpet",
    aspect: "portrait",
  },
  {
    id: "v3",
    type: "video",
    src: "/videos/gallery/carpet-sanitization-process-dubai.mp4",
    poster: "/videos/gallery/carpet-sanitization-process-dubai-poster.jpg",
    alt: "Carpet sanitization process removing bacteria and allergens in Dubai home",
    title: "Carpet Sanitization",
    category: "carpet",
    aspect: "portrait",
  },
  {
    id: "v4",
    type: "video",
    src: "/videos/gallery/carpet-shampooing-result-dubai.mp4",
    poster: "/videos/gallery/carpet-shampooing-result-dubai-poster.jpg",
    alt: "Professional carpet shampooing deep clean result in Dubai residential property",
    title: "Carpet Shampooing Result",
    category: "carpet",
    aspect: "portrait",
  },
  {
    id: "v5",
    type: "video",
    src: "/videos/gallery/carpet-stain-removal-process-dubai.mp4",
    poster: "/videos/gallery/carpet-stain-removal-process-dubai-poster.jpg",
    alt: "Stubborn stain removal from carpet using professional techniques in Dubai",
    title: "Carpet Stain Removal",
    category: "stain",
    aspect: "portrait",
  },
  {
    id: "v6",
    type: "video",
    src: "/videos/gallery/rug-cleaning-before-after-dubai.mp4",
    poster: "/videos/gallery/rug-cleaning-before-after-dubai-poster.jpg",
    alt: "Rug cleaning before and after showing dramatic cleaning results in Dubai",
    title: "Rug Cleaning Before & After",
    category: "rug",
    aspect: "portrait",
  },
  {
    id: "v7",
    type: "video",
    src: "/videos/gallery/sofa-cleaning-before-after-dubai.mp4",
    poster: "/videos/gallery/sofa-cleaning-before-after-dubai-poster.jpg",
    alt: "Sofa cleaning before and after result showing fabric restoration in Dubai",
    title: "Sofa Cleaning Before & After",
    category: "sofa",
    aspect: "portrait",
  },
  {
    id: "v8",
    type: "video",
    src: "/videos/gallery/sofa-cleaning-result-dubai.mp4",
    poster: "/videos/gallery/sofa-cleaning-result-dubai-poster.jpg",
    alt: "Professional sofa deep cleaning result with stain-free upholstery in Dubai",
    title: "Sofa Deep Clean Result",
    category: "sofa",
    aspect: "portrait",
  },
  {
    id: "v9",
    type: "video",
    src: "/videos/gallery/sofa-steam-cleaning-dubai.mp4",
    poster: "/videos/gallery/sofa-steam-cleaning-dubai-poster.jpg",
    alt: "Sofa steam cleaning sanitization process by Alhaya professionals in Dubai",
    title: "Sofa Steam Cleaning",
    category: "sofa",
    aspect: "portrait",
  },

  // --- IMAGES: Professional gallery photos ---
  {
    id: "i1",
    type: "image",
    src: "/images/gallery/professional-carpet-cleaning-technician-dubai.webp",
    alt: "Professional carpet cleaning technician deep cleaning oriental rug in Dubai",
    title: "Professional Technician at Work",
    category: "carpet",
    aspect: "landscape",
  },
  {
    id: "i2",
    type: "image",
    src: "/images/gallery/commercial-carpet-cleaning-technician-uae.webp",
    alt: "Commercial carpet cleaning technician with industrial equipment servicing offices across UAE",
    title: "Commercial Carpet Cleaning",
    category: "carpet",
    aspect: "landscape",
  },
  {
    id: "i3",
    type: "image",
    src: "/images/gallery/carpet-shampoo-deep-cleaning-dubai.webp",
    alt: "Carpet shampoo deep cleaning service showing professional results in Dubai",
    title: "Deep Shampoo Cleaning",
    category: "carpet",
    aspect: "landscape",
  },
  {
    id: "i4",
    type: "image",
    src: "/images/gallery/industrial-carpet-cleaning-machine-dubai.webp",
    alt: "Industrial carpet cleaning machine extracting dirt and stains from residential carpet",
    title: "Industrial Cleaning Equipment",
    category: "carpet",
    aspect: "landscape",
  },
  {
    id: "i5",
    type: "image",
    src: "/images/gallery/deep-carpet-cleaning-process-uae.webp",
    alt: "Deep carpet cleaning process removing embedded stains and odors across UAE",
    title: "Deep Cleaning Process",
    category: "carpet",
    aspect: "landscape",
  },
  {
    id: "i6",
    type: "image",
    src: "/images/gallery/professional-carpet-cleaning-team-dubai.webp",
    alt: "Professional carpet cleaning team from Alhaya Cleaning Services in Dubai",
    title: "Our Professional Team",
    category: "carpet",
    aspect: "landscape",
  },
  {
    id: "i7",
    type: "image",
    src: "/images/gallery/carpet-steam-extraction-cleaning-uae.webp",
    alt: "Carpet steam extraction hot water cleaning method sanitizing carpets across UAE",
    title: "Steam Extraction Cleaning",
    category: "carpet",
    aspect: "landscape",
  },
  {
    id: "i8",
    type: "image",
    src: "/images/gallery/clean-carpet-after-professional-cleaning-dubai.webp",
    alt: "Clean fresh carpet result after professional deep shampoo cleaning in Dubai",
    title: "Fresh Clean Result",
    category: "carpet",
    aspect: "landscape",
  },

  // --- IMAGES: Before-after photos ---
  {
    id: "ba1",
    type: "image",
    src: "/images/gallery/before-after-1.jpeg",
    alt: "Carpet cleaning before and after result showing stain removal in Dubai",
    title: "Before & After: Stain Removal",
    category: "stain",
    aspect: "landscape",
  },
  {
    id: "ba2",
    type: "image",
    src: "/images/gallery/before-after-2.jpeg",
    alt: "Carpet deep cleaning before and after comparison in Dubai home",
    title: "Before & After: Deep Clean",
    category: "carpet",
    aspect: "landscape",
  },
  {
    id: "ba3",
    type: "image",
    src: "/images/gallery/before-after-3.jpeg",
    alt: "Professional carpet shampooing before and after result in Dubai",
    title: "Before & After: Shampooing",
    category: "carpet",
    aspect: "landscape",
  },
  {
    id: "ba4",
    type: "image",
    src: "/images/gallery/before-after-4.jpeg",
    alt: "Carpet stain treatment before and after showing dramatic improvement",
    title: "Before & After: Stain Treatment",
    category: "stain",
    aspect: "landscape",
  },
  {
    id: "ba5",
    type: "image",
    src: "/images/gallery/before-after-5.jpeg",
    alt: "Rug cleaning before and after result by Alhaya professionals in Dubai",
    title: "Before & After: Rug Cleaning",
    category: "rug",
    aspect: "landscape",
  },
  {
    id: "ba6",
    type: "image",
    src: "/images/gallery/before-after-6.jpeg",
    alt: "Sofa upholstery cleaning before and after result in Dubai",
    title: "Before & After: Sofa Clean",
    category: "sofa",
    aspect: "landscape",
  },
  {
    id: "ba7",
    type: "image",
    src: "/images/gallery/before-after-7.jpeg",
    alt: "Carpet sanitization before and after comparison showing fresh clean result",
    title: "Before & After: Sanitization",
    category: "carpet",
    aspect: "landscape",
  },
  {
    id: "ba8",
    type: "image",
    src: "/images/gallery/before-after-8.jpeg",
    alt: "Professional carpet odor removal before and after result in Dubai",
    title: "Before & After: Odor Removal",
    category: "carpet",
    aspect: "landscape",
  },

  // --- IMAGES: Carpet result photos ---
  {
    id: "c1",
    type: "image",
    src: "/images/carpet/carpet-cleaning-before-after-dubai.webp",
    alt: "Carpet cleaning before and after comparison in Dubai residential property",
    title: "Residential Carpet Result",
    category: "carpet",
    aspect: "landscape",
  },
  {
    id: "c2",
    type: "image",
    src: "/images/carpet/carpet-cleaning-results-dubai.webp",
    alt: "Professional carpet cleaning results showing pristine finish in Dubai",
    title: "Pristine Carpet Finish",
    category: "carpet",
    aspect: "landscape",
  },
  {
    id: "c3",
    type: "image",
    src: "/images/carpet/carpet-deep-cleaning-villa-dubai.webp",
    alt: "Villa carpet deep cleaning service with complete room restoration in Dubai",
    title: "Villa Deep Cleaning",
    category: "carpet",
    aspect: "landscape",
  },
  {
    id: "c4",
    type: "image",
    src: "/images/carpet/commercial-office-carpet-cleaning-uae.webp",
    alt: "Commercial office carpet cleaning result across UAE by Alhaya Cleaning",
    title: "Office Carpet Cleaning",
    category: "carpet",
    aspect: "landscape",
  },
  {
    id: "c5",
    type: "image",
    src: "/images/carpet/carpet-cleaning-apartment-uae.webp",
    alt: "Apartment carpet cleaning with fresh sanitized result in UAE",
    title: "Apartment Carpet Clean",
    category: "carpet",
    aspect: "landscape",
  },
  {
    id: "c6",
    type: "image",
    src: "/images/carpet/carpet-cleaning-residential-dubai.webp",
    alt: "Residential carpet cleaning service with eco-friendly products in Dubai",
    title: "Eco-Friendly Home Clean",
    category: "carpet",
    aspect: "landscape",
  },
  {
    id: "c7",
    type: "image",
    src: "/images/carpet/carpet-cleaning-commercial-uae.webp",
    alt: "Commercial carpet cleaning for large-scale offices and businesses across UAE",
    title: "Commercial Cleaning",
    category: "carpet",
    aspect: "landscape",
  },
];
